src/Entity/Urls.php
<?php

namespace App\Entity;

use App\Repository\UrlsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UrlsRepository::class)
 */
class Urls
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $estado;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $comentario;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $creation_date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="urls")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="url")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getEstado(): ?bool
    {
        return $this->estado;
    }

    public function setEstado(?bool $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getComentario(): ?string
    {
        return $this->comentario;
    }

    public function setComentario(string $comentario): self
    {
        $this->comentario = $comentario;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(?\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Form/UrlsType.php
<?php

namespace App\Form;

use App\Entity\Urls;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UrlsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
            ->add('estado')
            ->add('comentario')
            ->add('creation_date')
            ->add('user')
            ->add('category')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Urls::class,
        ]);
    }
}

src/Controller/UrlsController.php
<?php

namespace App\Controller;

use App\Entity\Urls;
use App\Form\UrlsType;
use App\Repository\UrlsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/urls')]
class UrlsController extends AbstractController
{
    #[Route('/', name: 'urls_index', methods: ['GET'])]
    public function index(UrlsRepository $urlsRepository): Response
    {
        return $this->render('urls/index.html.twig', [
            'urls' => $urlsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'urls_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $url = new Urls();
        $form = $this->createForm(UrlsType::class, $url);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($url);
            $entityManager->flush();

            return $this->redirectToRoute('urls_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('urls/new.html.twig', [
            'url' => $url,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'urls_show', methods: ['GET'])]
    public function show(Urls $url): Response
    {
        return $this->render('urls/show.html.twig', [
            'url' => $url,
        ]);
    }

    #[Route('/{id}/edit', name: 'urls_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Urls $url): Response
    {
        $form = $this->createForm(UrlsType::class, $url);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('urls_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('urls/edit.html.twig', [
            'url' => $url,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'urls_delete', methods: ['POST'])]
    public function delete(Request $request, Urls $url): Response
    {
        if ($this->isCsrfTokenValid('delete'.$url->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($url);
            $entityManager->flush();
        }

        return $this->redirectToRoute('urls_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/urls/_delete_form.html.twig
<form method="post" action="{{ path('urls_delete', {'id': url.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ url.id) }}">
    <button class="btn">Delete</button>
</form>

templates/urls/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/urls/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Urls{% endblock %}

{% block body %}
    <h1>Edit Urls</h1>

    {{ include('urls/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('urls_index') }}">back to list</a>

    {{ include('urls/_delete_form.html.twig') }}
{% endblock %}

templates/urls/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Urls index{% endblock %}

{% block body %}
    <h1>Urls index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Estado</th>
                <th>Comentario</th>
                <th>Creation_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for url in urls %}
            <tr>
                <td>{{ url.id }}</td>
                <td>{{ url.nombre }}</td>
                <td>{{ url.estado ? 'Yes' : 'No' }}</td>
                <td>{{ url.comentario }}</td>
                <td>{{ url.creationDate ? url.creationDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('urls_show', {'id': url.id}) }}">show</a>
                    <a href="{{ path('urls_edit', {'id': url.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('urls_new') }}">Create new</a>
{% endblock %}

templates/urls/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Urls{% endblock %}

{% block body %}
    <h1>Create new Urls</h1>

    {{ include('urls/_form.html.twig') }}

    <a href="{{ path('urls_index') }}">back to list</a>
{% endblock %}

templates/urls/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Urls{% endblock %}

{% block body %}
    <h1>Urls</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ url.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ url.nombre }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ url.estado ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Comentario</th>
                <td>{{ url.comentario }}</td>
            </tr>
            <tr>
                <th>Creation_date</th>
                <td>{{ url.creationDate ? url.creationDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('urls_index') }}">back to list</a>

    <a href="{{ path('urls_edit', {'id': url.id}) }}">edit</a>

    {{ include('urls/_delete_form.html.twig') }}
{% endblock %}